version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yuwah_development
      POSTGRES_USER: yuwah
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://yuwah:password@db:5432/yuwah_development

volumes:
  postgres_data: