development:
  secret_key_base: abcdefghijklmnopqrstuvwxyz
  tokens_key: abcdefghijklmnopqrstuvwxyz
test:
  secret_key_base: abcdefghijklmnopqrstuvwxyz
  tokens_key: abcdefghijklmnopqrstuvwxyz
production:
  secret_key_base: 61fd714642a4b9f227d5564b85ff0fbe836d667c2ecb32cb46db70e3b13e9b1bede7f3945540e0793f616e18ca4caa10c0f915201095029f84c7a84b672d7eaa
  tokens_key: 196f9fb2f40659880aed12594b9aceab